# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

# When using Hugo Modules this config value should be removed.
#theme = "congo"

baseURL = "https://alainwolf.ch/"
languageCode = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true
pagination.pagerSize = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.author]
  name = "Alain Wolf"
  image = "img/author.png"
  headline = "Don't panic!"
  links = [
    { email = "mailto:alain@alainwolf.ch" },
    { signal-messenger = "https://signal.me/#eu/mEXHzaYIpE4Ilr4n6w7z7WhP0CoWGs4_ceiSrTNzCri7czEG1WZDpbwCS4s1DYgK" },
    { github = "https://github.com/alainwolf" },
    { keybase = "https://keybase.io/alainwolf" },
    { soundcloud = "https://soundcloud.com/alainwolf" },
    { stack-overflow = "https://stackoverflow.com/users/4719048/alain-wolf" },
    { steam = "https://steamcommunity.com/id/gusag64/" },
    { openbroadcast = "https://www.openbroadcast.org/network/users/b8cfebd6-2cfa-4d46-a34f-d16a524147b9/profile/" },
  ]

[languages]
  [languages.en]
    languageCode = "en"
    languageName = 'English'
    languageDirection = 'ltr'
    weight = 1
    copyright = "© 2024 Alain Wolf - All rights reserved"
    title = "Alain Wolf"

    [languages.en.params]
      dateFormat = "January 2, 2006"
      description = "Personal Website vof Alain Wolf, Zurich, Switzerland"

  [languages.de]
    languageCode = "de"
    languageName = "Deutsch"
    title = "Alain Wolf"
    weight = 2
    copyright = "© 2024 Alain Wolf - Alle Rechte vorbehalten"

    [languages.de.params]
      dateFormat = "2. January 2006"
      description = "Persönliche Website von Alain Wolf, Zürich, Schweiz"

[privacy]
  [privacy.googleAnalytics]
    disable = true

  [privacy.disqus]
    disable = true

  [privacy.instagram]
    disable = true

  [privacy.twitter]
    disable = true

  [privacy.vimeo]
    disable = true

  [privacy.youtube]
    disable = true
